[package]
name = "copperdb-replication"
description = "Raft-based consensus and replication: leader election, log replication, HA standby"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
tokio.workspace = true
tracing.workspace = true
copperdb-storage = { workspace = true }
copperdb-topology = { workspace = true }
