[package]
name = "copperdb-search"
description = "Full-text and semantic search capabilities"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tantivy.workspace = true
regex.workspace = true
copperdb-storage = { workspace = true }
copperdb-indexing = { workspace = true }
copperdb-topology = { workspace = true }
copperdb-util = { workspace = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "lucene_fulltext"
harness = false
