[package]
name = "copperdb-pool"
description = "Connection pool for database driver connections"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
parking_lot.workspace = true
tracing.workspace = true
copperdb-util = { workspace = true }
