[package]
name = "copperdb-storage"
description = "Embedded key-value storage engine (replaces Badger/BadgerDB)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
bytes.workspace = true
rmp-serde.workspace = true
parking_lot.workspace = true
tracing.workspace = true
uuid.workspace = true
fjall.workspace = true
tempfile.workspace = true
hex.workspace = true
copperdb-util = { workspace = true }
copperdb-topology = { workspace = true }
copperdb-encryption = { workspace = true }
copperdb-kms = { workspace = true }
