[package]
name = "copperdb-inference"
description = "ML model inference pipeline: embedding, classification, generation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
copperdb-embed = { workspace = true }
copperdb-localllm = { workspace = true }
copperdb-util = { workspace = true }
