[package]
name = "copperdb-embeddingutil"
description = "Embedding utility functions: normalization, similarity metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
nalgebra.workspace = true
tracing.workspace = true
copperdb-math = { workspace = true }
copperdb-util = { workspace = true }
