[package]
name = "copperdb-embed"
description = "Text embedding generation: OpenAI API and local GGUF model support"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
tracing.workspace = true
libloading.workspace = true
parking_lot.workspace = true
copperdb-util = { workspace = true }
async-trait.workspace = true
