[package]
name = "magnetdb-fabric"
description = "Distributed fabric: multi-datacenter routing and workload distribution"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
magnetdb-replication = { workspace = true }
magnetdb-util = { workspace = true }
