[package]
name = "copperdb-admin"
description = "Offline administrative commands for copperdb"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "copperdb-admin"
path = "src/main.rs"

[dependencies]
clap.workspace = true
copperdb-adminimport.workspace = true
copperdb-localization.workspace = true
copperdb-storage.workspace = true
copperdb-util.workspace = true
sys-locale.workspace = true