[package]
name = "copperdb"
description = "copperdb executable server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
hex.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rustls.workspace = true
serde_json.workspace = true
copperdb-kms = { workspace = true }
copperdb-bolt = { workspace = true }
copperdb-buildinfo = { workspace = true }
copperdb-config = { workspace = true }
copperdb-lifecycle = { workspace = true }
copperdb-multidb = { workspace = true }
copperdb-server = { workspace = true }
copperdb-otel = { workspace = true }
