[package]
name = "magnetdb-eval"
description = "Cypher query evaluator: AST execution against the storage engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
magnetdb-cypher = { workspace = true }
magnetdb-storage = { workspace = true }
magnetdb-cache = { workspace = true }
magnetdb-util = { workspace = true }
