[package]
name = "copperdb-filter"
description = "Result set filtering: predicate evaluation, type coercion"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
tracing.workspace = true
copperdb-cypher = { workspace = true }
copperdb-util = { workspace = true }
